services:
  validator:
    image: ethereum/client-go:v1.11.3
    restart: always
    working_dir: /validator
    hostname: validator
    volumes:
      - ./:/validator
    ports:
      - 30333:30333
    command: |
      --networkid 224
      --syncmode "full"
      --mine
      --miner.etherbase 0xAEc0F742161064E6290f3CE213205993D8A0A1B1
      --miner.gasprice 1000000
      --miner.gaslimit 800000000
      --nat extip:192.168.1.39
      --datadir "node"
      --nousb
      --password password.txt
      --unlock 0xAEc0F742161064E6290f3CE213205993D8A0A1B1
      --port 30333
      --bootnodes ""
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "1"
