services:
  validator:
    image: ethereum/client-go:v1.11.3
    restart: always
    working_dir: /validator
    hostname: validator
    volumes:
      - ./:/validator
    ports:
      - 30333:30333
    command: |
      --networkid 224
      --syncmode "full"
      --mine
      --miner.etherbase 0x2586d69e9504e679c8e99Cc0Dd6AAeD98160468e
      --miner.gasprice 10000000000
      --miner.gaslimit 40000000
      --nat extip:192.168.1.39
      --datadir "node"
      --nousb
      --password password.txt
      --unlock 0x2586d69e9504e679c8e99Cc0Dd6AAeD98160468e
      --port 30333
      --bootnodes ""
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "1"
